set_property IOSTANDARD LVCMOS18 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[0]}]
set_property IOSTANDARD LVDS [get_ports SYSCLK_P]
set_property IOSTANDARD LVCMOS18 [get_ports SYS_RESET]
set_property PACKAGE_PIN E19 [get_ports SYSCLK_P]
set_property PACKAGE_PIN AV40 [get_ports SYS_RESET]
set_property PACKAGE_PIN AM39 [get_ports {LED[0]}]
set_property PACKAGE_PIN AN39 [get_ports {LED[1]}]
set_property PACKAGE_PIN AR37 [get_ports {LED[2]}]
set_property PACKAGE_PIN AT37 [get_ports {LED[3]}]
set_property PACKAGE_PIN AR35 [get_ports {LED[4]}]
set_property PACKAGE_PIN AP41 [get_ports {LED[5]}]
set_property PACKAGE_PIN AP42 [get_ports {LED[6]}]
set_property PACKAGE_PIN AU39 [get_ports {LED[7]}]




set_property PACKAGE_PIN AR40 [get_ports {BUTTON[0]}]
set_property PACKAGE_PIN AU38 [get_ports {BUTTON[1]}]
set_property PACKAGE_PIN AP40 [get_ports {BUTTON[2]}]
set_property PACKAGE_PIN AW40 [get_ports {BUTTON[3]}]
set_property PACKAGE_PIN AV39 [get_ports {BUTTON[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BUTTON[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BUTTON[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BUTTON[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BUTTON[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BUTTON[0]}]
set_property PACKAGE_PIN AV30 [get_ports {SW[0]}]
set_property PACKAGE_PIN AY33 [get_ports {SW[1]}]
set_property PACKAGE_PIN BA31 [get_ports {SW[2]}]
set_property PACKAGE_PIN BA32 [get_ports {SW[3]}]
set_property PACKAGE_PIN AW30 [get_ports {SW[4]}]
set_property PACKAGE_PIN AY30 [get_ports {SW[5]}]
set_property PACKAGE_PIN BA30 [get_ports {SW[6]}]
set_property PACKAGE_PIN BB31 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[0]}]



