set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[0]}]
set_property PACKAGE_PIN BB31 [get_ports {GPIO_DIP[7]}]
set_property PACKAGE_PIN BA30 [get_ports {GPIO_DIP[6]}]
set_property PACKAGE_PIN AY30 [get_ports {GPIO_DIP[5]}]
set_property PACKAGE_PIN AW30 [get_ports {GPIO_DIP[4]}]
set_property PACKAGE_PIN BA32 [get_ports {GPIO_DIP[3]}]
set_property PACKAGE_PIN BA31 [get_ports {GPIO_DIP[2]}]
set_property PACKAGE_PIN AY33 [get_ports {GPIO_DIP[1]}]
set_property PACKAGE_PIN AV30 [get_ports {GPIO_DIP[0]}]
set_property PACKAGE_PIN AM39 [get_ports {GPIO_LED[0]}]
set_property PACKAGE_PIN AN39 [get_ports {GPIO_LED[1]}]
set_property PACKAGE_PIN AR37 [get_ports {GPIO_LED[2]}]
set_property PACKAGE_PIN AT37 [get_ports {GPIO_LED[3]}]
set_property PACKAGE_PIN AR35 [get_ports {GPIO_LED[4]}]
set_property PACKAGE_PIN AP41 [get_ports {GPIO_LED[5]}]
set_property PACKAGE_PIN AP42 [get_ports {GPIO_LED[6]}]
set_property PACKAGE_PIN AU39 [get_ports {GPIO_LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports RST]
set_property PACKAGE_PIN AV40 [get_ports RST]
set_property PACKAGE_PIN AH8 [get_ports SGMIICLK_P]
set_property PACKAGE_PIN AN2 [get_ports SGMII_TXP]
set_property PACKAGE_PIN AJ33 [get_ports PHY_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports PHY_RESET]

create_clock -period 8.000 -name SGMII_P -waveform {0.000 4.000} [get_ports SGMIICLK_P]

set_property PACKAGE_PIN E19 [get_ports SYSCLK_P]
set_property IOSTANDARD LVDS [get_ports SYSCLK_P]
set_property IOSTANDARD LVDS [get_ports SYSCLK_N]

create_clock -period 5.000 -name SYSCLK -waveform {0.000 2.500} [get_ports SYSCLK_P]
